### ISSUE TITLE
Add info regarding how voting works

### ISSUE THREAD

**Issue by Erol314** [brendt/rfc-vote#104]
As a person who first time sees this page, it wont be obvious to me that arguments are counted as votes too.
These details on how voting works would be nice to have on the voting page.

**Comment by brendt** [comment]
I agree. Do you have any suggestions on what would be helpful? We could add a "how voting works" section, but I'm not sure whether many people will read it. I'm more then happy to code things, but I would like to get some input.

**Comment by Erol314** [comment]
> I agree. Do you have any suggestions on what would be helpful? We could add a "how voting works" section, but I'm not sure whether many people will read it. I'm more then happy to code things, but I would like to get some input.

I think making it in separate tab is not the best. 
I think it has to be visible on every rfc vote page.
Also the message must be short (to my taste).
Maybe somewhere here would be good place.
![image](https://github.com/brendt/rfc-vote/assets/24621490/c7263a85-6189-4765-b46e-599854060f70)
Regarding the wording, need to think a bit

**Comment by brendt** [comment]
<img width="1281" alt="Screenshot 2023-08-16 at 14 12 55" src="https://github.com/brendt/rfc-vote/assets/6905297/d20a9bac-8032-4521-a96d-21a9886ae4a7">

I added this for now, but I think it can improved on (it's a bit too long imo).

Keep sharing your ideas! :)
