### ISSUE TITLE
Add indication of a user's vote on the RFC card on the homepage when logged in

### ISSUE THREAD

**Issue by jklmnop** [brendt/rfc-vote#108]
On the homepage there will eventually be many RFCs. Right now, there is no way to know if you voted on something without relying on your own memory.

For example, I voted on Short Closures, but there is no indication on the RFC card on the homepage that I did that.

<img width="839" alt="image" src="https://github.com/brendt/rfc-vote/assets/180323/50700468-910b-4443-817c-210dcd268c3d">

**Comment by brendt** [comment]
Agree, right now it's confusing.

**Comment by SerhiiCho** [comment]
I think you need to close this manually @brendt

**Comment by jklmnop** [comment]
❤️ fantastic!
