### ISSUE TITLE
Feature Request: Notification email on new RFCs to vote for

### ISSUE THREAD

**Issue by BobDankert** [brendt/rfc-vote#109]
I love this! A feature request I'd love to see - get a notification email when new RFCs are available to vote on. I don't want to forget about this and then the next RFC's have no votes!

It might also be nice to change it from "RFC Vote", which sounds very official, to something like "RFC Public Opinion" to better clarify that these votes don't have an official impact. Just a thought.

Bob

**Comment by vsergiu93** [comment]
I would also like to have some sort of a notification when a new rfc has been created/published. 

Actually it would be nice to send a email notification when the rfc vote has ended, the email notification could contain the 
result of the vote and maybe the top 5 most voted arguments (maybe not the full argument as that can become quite long).

But I think sending an email notification when a new rfc is ready for voting and when a rfc has closed/ended it would be nice.

**Comment by Atulin** [comment]
Definitely. Honestly, as it is now, and with the URL it has now, I'll just forget the site exists in a week. An email, a push notification, or something similar would be a great reminder.

**Comment by brendt** [comment]
I made this issue where I'll bundle everything related to email updates. Feel free to share your thoughts: https://github.com/brendt/rfc-vote/issues/117
