### ISSUE TITLE
Default jetstream routes still accessible

### ISSUE THREAD

**Issue by whoami15** [brendt/rfc-vote#121]
After clicking **edit profile** inside the Resend email verification page. I am redirected to `user/profile` which is the default route of Jetstream and am able to see another version of the profile page.

Resend email verification page:

![Screenshot 2023-08-17 162649](https://github.com/brendt/rfc-vote/assets/16274153/7cee39ca-0c57-4364-b90e-758d6fb4182c)
`user/profile` page:

![Screenshot 2023-08-17 162743](https://github.com/brendt/rfc-vote/assets/16274153/40a8cb54-273d-4313-8792-396de83ed87c)

To remove the default routes of Jetstream, we need to ignore it inside the `register` method of the `JetstreamServiceProvider`.

```php
public function register(): void
{
    // Ignore the default Jetstream routes.
    Jetstream::ignoreRoutes();
}
```

**Comment by brendt** [comment]
I've removed the profile link. I wanna keep the jetstream routes for a little longer though, just in case we've missed something.
