### ISSUE TITLE
User flair for core php-src maintainers

### ISSUE THREAD

**Issue by olleharstedt** [brendt/rfc-vote#147]
Some users' opinion on internal technical matters might weigh heavier than others. :) If I say "generics is possible to implement in the PHP engine" it doesn't mean much, because I'm not a core php-src maintainer. To highlight technical expertise during discussions, some users could have verified badges next to the user name, like "core PHP maintainer". Other labels might be relevant too, for framework maintainers, extension maintainers, people with voter rights, etc.

This is similar to certain subreddits where users can be verified as professional doctors or historians.

The user should probably be able to change which verified label to show or hide at any point.

**Comment by vsergiu93** [comment]
I think this is a great idea. I guess that some of this validation steps can also be automated in some ways, like framework maintainers there has to be some ways to get this info from github api.

As I'm thinking more about this, I fee that we do need to implement some sort of validation process and have some sort of verified badge, think of it as a general validation badge and I think it can be easily implemented.

What if we consider github as some sort of verification processor, what I mean by that is that any user registered with github it is automatically validated/verified, users who registered through the web form have a button somewhere to link their account with github.

I think in the end, what I'm saying is that users will not be able to just simply paste a link to a github profile, they actually have to link their account with github, in this way I know for sure that the user actually owns that github account.

**Comment by brendt** [comment]
Verifying with GitHub was actually the exact idea I was thinking about as well. I'm gonna focus on the special badge case first, and then work in automation.

**Comment by brendt** [comment]
TODO:

- [ ] Finish the TODO paragraph in the profile form
- [ ] Style the flair itself
- [ ] Maybe we need predefined flair color sets for foreground and background, so that you don't have to pick a random hex

**Comment by brendt** [comment]
We need to restyle this

<img width="323" alt="Screenshot 2023-08-21 at 11 30 17" src="https://github.com/brendt/rfc-vote/assets/6905297/e65ea72b-b48f-42b1-996b-ca53ce26e7c8">


@SerhiiCho do you have any input?

**Comment by SerhiiCho** [comment]
I would have been nice instead of adding `flair` and `flair_color` columns, add `flairs` table with all the needed flairs data. Also `flair_user` table to connect user and flair. I would have been better in the long run.

Because if we change flair color, we'll need to change this color for every user that already have `flair_color` assigned to them.

**Comment by brendt** [comment]
Great idea. Maybe it's ok to keep them in an enum though? I don't think we need to make them dynamic, as there will only be a handful of flair types in total.

Do you perhaps also have an idea about how we can style flairs in the argument cards?

**Comment by SerhiiCho** [comment]
> Do you perhaps also have an idea about how we can style flairs in the argument cards?

Yeah, I would personally go for colorless version like this:
<img width="340" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/4e04544e-02fb-434a-a906-320812623c69">

I don't think that if user is admin or contributor to PHP source needs to be associated to some color

**Comment by brendt** [comment]
Makes sense, I like it! Do you want to submit a PR?

**Comment by brendt** [comment]
It's done :)

For now, admins, contributors and internals can apply for a badge.

**Comment by olleharstedt** [comment]
Hooray!
