### ISSUE TITLE
Style admin pages

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#151]
Admin pages are a mess 😅

<img width="1917" alt="Screenshot 2023-08-21 at 11 30 32" src="https://github.com/brendt/rfc-vote/assets/6905297/f72a5f82-8165-49c9-b174-1a8b402e434f">

**Comment by SerhiiCho** [comment]
How do you navigate to this page? I haven't found any links except the one that is up on the navbar.

**Comment by brendt** [comment]
<img width="586" alt="Screenshot 2023-08-21 at 14 28 15" src="https://github.com/brendt/rfc-vote/assets/6905297/009edaf0-8671-44a9-b160-42839d31b9ef">

These are links 😅 It's still a huge WIP

**Comment by RubenSteen** [comment]
@brendt I cannot find these links either, there is also nothing that points to some sort of page in the routes file.

![image](https://github.com/brendt/rfc-vote/assets/17903622/f691996a-ca74-4716-a1d8-b66cf05cc044)

**Comment by SerhiiCho** [comment]
It's because it's WIP (Work in progress). It's on a development branch

**Comment by brendt** [comment]
Exactly, that's the branch :) I'll probably merge it today though
