### ISSUE TITLE
Clean up code base

### ISSUE THREAD

**Issue by carakas** [brendt/rfc-vote#152]
There is old code left in the code base like https://github.com/brendt/rfc-vote/blob/3e4f89eb0d45c7e719ddc5bfdfb818da54b57edc/resources/views/components/user-reputation.blade.php that is no longer used.
I don't know if there are more parts like this but it would be better to remove it than leave it in the codebase since it can confuse people when searching in the code

**Comment by SerhiiCho** [comment]
The `user-reputation` is used within `user-reputation-counter`, which is literally one line:
```php
<x-user-reputation :user="$user"/>
```
