### ISSUE TITLE
Push "not seen" arguments to the top or make a sort element

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#156]
Isn't it better to sort the arguments so that "not seen" arguments are at the top of the list? Because occasionally, I visit the RFC to just check if there are some good new arguments, and I need to scroll and search them specifically.

![image](https://github.com/brendt/rfc-vote/assets/35465417/c3a6907a-5dbf-4daf-9171-429497663c97)

Another solution will be to add a sort select element, where you can choose to sort by "New", "Old", "Most voted", "Least voted".

**Comment by brendt** [comment]
Yeah I think being able to sort makes sense. I'll work on it

**Comment by brendt** [comment]
@SerhiiCho I wanted your opinion: I plan working on this issue, but I would really like to re-introduce the colored borders for new arguments. I find that the `new` badge in the footer doesn't stand out enough. What are your thoughts on it? I'll of course also add a filter as described in this issue.

**Comment by SerhiiCho** [comment]
I think we can add a 1px border. I like the blue border that github has on new comments on isses and prs. Maybe we can do something like that, just use our purple color

**Comment by brendt** [comment]
>  I like the blue border that github has on new comments on isses and prs.

I was thinking exactly the same when I read your comment 😁
<img width="891" alt="Screenshot 2023-09-01 at 07 17 36" src="https://github.com/brendt/rfc-vote/assets/6905297/970c9f25-ce8c-4e94-b339-5a0456915b03">

**Comment by SerhiiCho** [comment]
I think we'll also need to remove shadows from arguments and make them look a bit more like github has. Shadow with border will not look good

**Comment by Plytas** [comment]
I suggest using tailwind `.ring` class instead of border as it won't affect the layout.

**Comment by Plytas** [comment]
I think that's exactly what GitHub is doing as well. They use border as well, but only for the rounding of the corners, the actual color comes from box shadow.
<img width="327" alt="image" src="https://github.com/brendt/rfc-vote/assets/17316322/35768c17-fde3-4320-8028-95eb7306685e">

**Comment by brendt** [comment]
I made a sorter! 

Might need some more styling? Feel free to take a look if you want @SerhiiCho (or someone else)

<img width="1246" alt="Screenshot 2023-09-01 at 11 15 47" src="https://github.com/brendt/rfc-vote/assets/6905297/808c5d09-2633-43df-af0e-5ba70e743a1a">

**Comment by SerhiiCho** [comment]
Thanks @brendt, it's a great improvement... I'll definitely tweak some styles a bit
