### ISSUE TITLE
add corresponding externals discussion

### ISSUE THREAD

**Issue by Erol314** [brendt/rfc-vote#162]
Before voting for me it is interesting to read the context (related externals discussion);

add the link(s) to the externals discussion to the rfcvote page

**Comment by brendt** [comment]
Yes! If anyone wants to take a look, feel free to send a PR

**Comment by Plytas** [comment]
What's a good way to get externals discussion link?

**Comment by brendt** [comment]
Manually, I think 😅

What we could do in the future is to import it via the externals RSS feed, but for that to work, we also need to import RFC data (which is work in progress: #182 )

So, if we already have a field that can be edited by admins, and properly show it on the RFC page, that's already great.

**Comment by Plytas** [comment]
Opened #235

**Comment by brendt** [comment]
Nice, deploying now :)
