### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by MohammadAlhallaq** [brendt/rfc-vote#174]
I've just started working on the dark mode. Wish me luck, as Brendt isn't a fan of dark themes :)

**Comment by MohammadAlhallaq** [comment]
> I also though about that... good luck @MohammadAlhallaq . There is a `_variables.css` file, you can put all new variables in it. Here is how I did in other project just as an example:
> 
> ```css
> :root {
>     --color-page: white;
>     --color-page-second: #f1f1f1;
>     --color-border: #0000001a;
>     --color-font: #292929;
>     --color-font-second: #555;
>     --color-font-second-hover: #222;
>     --color-link: #145DA0;
>     --color-link-hover: #104f89;
> }
> .dark {
>     --color-page: #191e26;
>     --color-page-second: #1f252e;
>     --color-border: #ffffff1a;
>     --color-font: #afbaca;
>     --color-font-second: #a9a9a9;
>     --color-font-second-hover: #929292;
>     --color-link: #93adde;
>     --color-link-hover: #6881b1;
> }
> ```
> 
> and don't forget to add a `darkMode: 'class',` to tailwind config. Good luck! Thanks for the help. I know you probably know all of this, but saying this won't hurt

yeah definitely gonna make use of the variable file to keep things clean, also to avoid the overhead complexity the dark mode adds..

thanks buddy 👍🏻

**Comment by MohammadAlhallaq** [comment]
I've tried the following colors on the home page. What would you guys change about it? I feel there's something off, but I can't quite tell what it is @Erol314 @SerhiiCho.

![image](https://github.com/brendt/rfc-vote/assets/19909432/699df030-7b4f-4ed8-a170-c79fad0caa2a)

**Comment by Erol314** [comment]
@MohammadAlhallaq overall I can say its nice )
reading these 2 articles I can say:
* The text is too white and bold which makes image 'vibrate'.
* white boxes like 'Check the repository' are still too bright
[1]https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/#aa-design-considerations


I personally like the background gray.

Can you raise draft PR so we can play a bit with it too ) ?

**Comment by brendt** [comment]
Yeah definitely feel free to open a PR.

SO THAT I CAN CLOSE IT!! 

No, just kidding. I'm fine with adding dark mode, even though I don't use it ;)

**Comment by MohammadAlhallaq** [comment]
I will open a draft PR once I get home :)

**Comment by SerhiiCho** [comment]
I also think the the color should be light gray instead of white. I'm a fan of dark color scheme on [laravel.com](https://laravel.com/docs/10.x) website. They use light gray font and they don't use black color anywhere as it's too deep

**Comment by MohammadAlhallaq** [comment]
going to close this issue as I've created a draft PR.

**Comment by Kamleshpaul** [comment]
@MohammadAlhallaq  i think you forgot this one?

<img width="192" alt="Screenshot 2023-08-30 at 10 28 28 AM" src="https://github.com/brendt/rfc-vote/assets/25585917/27d0506e-38bf-428b-99a4-d00411e54f5d">
