### ISSUE TITLE
Admin for managing users

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#175]
A basic CRUD overview for admin that display all the users. Right now it'll be useful to add badges to existing users.

**Comment by Kamleshpaul** [comment]
# Is this fine ? 
<img width="1340" alt="Screenshot 2023-09-01 at 1 29 34 PM" src="https://github.com/brendt/rfc-vote/assets/25585917/b02e4b75-abf9-4925-8799-d5795440057a">

**Comment by brendt** [comment]
Definitely. We don't have a proper frontend setup for admin screens yet, so this seems fine. The most important part is the edit form.

What I think I'd change in this view, data-wise:

- Put the avatar in front of the name (there's a component for that `x-username`)
- Align the buttons to the right
- Add the reputation and the badge

**Comment by Kamleshpaul** [comment]
### These are the update . let me know anything update
<img width="1350" alt="Screenshot 2023-09-01 at 6 54 19 PM" src="https://github.com/brendt/rfc-vote/assets/25585917/b27df005-ca0f-4be3-b85c-d1b3feb34eea">
<img width="1326" alt="Screenshot 2023-09-01 at 6 55 22 PM" src="https://github.com/brendt/rfc-vote/assets/25585917/69b8b86d-d775-43d8-8999-501d1614b3dd">

**Comment by brendt** [comment]
Could you submit a PR? There might be some details to address, but I'd need to see the code :)

**Comment by Kamleshpaul** [comment]
This is PR https://github.com/brendt/rfc-vote/pull/255
