### ISSUE TITLE
User flair notification

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#177]
We need to send notifications:

- To admin users when a verification request was submitted
- To users when their request was accepted
- To users when their request was denied

I propuse to use the in-app messages system, so we'll need to wait until #176 is merged

**Comment by olleharstedt** [comment]
> do you want to use `websocket` ? for this `in-app messages` like https://docs.soketi.app/

That sounds more like a "could-have" than a "should-have" or "must-have". :)

https://en.wikipedia.org/wiki/MoSCoW_method

**Comment by brendt** [comment]
At this point we don't need websockets :)

**Comment by brendt** [comment]
Fixed
