### ISSUE TITLE
Styling issue with loading animation on no argument upvote

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#199]
When you upvote a no argument, the loading button is shown, but the arrow isn't hidden while loading. The same doesn't happen with the yes button:

<img width="258" alt="Screenshot 2023-08-29 at 13 17 56" src="https://github.com/brendt/rfc-vote/assets/6905297/7da11a75-129a-44e1-8dfc-9ba5dd9104e8">
<img width="258" alt="Screenshot 2023-08-29 at 13 18 38" src="https://github.com/brendt/rfc-vote/assets/6905297/59cc7793-39f9-4cdb-83a6-96516bc18166">

**Comment by brendt** [comment]
@Kamleshpaul wanna take a look?

**Comment by SerhiiCho** [comment]
I'll take a look, I'm waiting until [this PR](https://github.com/brendt/rfc-vote/pull/181) will be merged, there are many changes, I would rather not create any conflicts

**Comment by Kamleshpaul** [comment]
@brendt  sure let me check this

**Comment by Plytas** [comment]
Couldn't reproduce it either.

**Comment by brendt** [comment]
Maybe it's with specific arguments?

This one on https://rfc.stitcher.io/rfc/short-closures-20 has the problem

<img width="1303" alt="Screenshot 2023-08-30 at 06 50 53" src="https://github.com/brendt/rfc-vote/assets/6905297/5b4a7ea5-f2a3-4cb7-a235-78db417c8904">

**Comment by Kamleshpaul** [comment]
it is working fine in my side

<img width="413" alt="Screenshot 2023-08-30 at 10 25 10 AM" src="https://github.com/brendt/rfc-vote/assets/25585917/05fca4ed-32e0-4245-b865-46d845bd88a7">

**Comment by brendt** [comment]
Let's assume it's an issue on my side then :) We'll close it for now
