### ISSUE TITLE
🎨 Redesign the about page

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#206]
I want to redesign the about me page since there are now contributors added to it 🤔 I'll post WIPs to get the feedback

Blocked by https://github.com/brendt/rfc-vote/pull/205

**Comment by brendt** [comment]
Go for it :) #205 is now merged :)

**Comment by SerhiiCho** [comment]
Is the word "Focus:" okay for highlighting the things that contributors are worked on? Maybe we just remove it so that we don't have to keep track of these things?

![image](https://github.com/brendt/rfc-vote/assets/35465417/b33230a8-7e7f-41c1-abc5-5138f2c211d0)

**Comment by Plytas** [comment]
My 2ct, I would remove word Focus and make the contributions different color, maybe gray-ish. Also, perhaps it would look tidier if the blocks were fixed width? Or maybe even fixed width, but alternate the count and offset in each row, so it looks like masonry brick effect?

**Comment by brendt** [comment]
Yeah, I don't think we need `focus`, I think it's clear on its own?

Where do you get the avatars from? GitHub?

**Comment by brendt** [comment]
Oh, random idea, we could link contributors to users on the app, also showing their reputation, etc. I can work on that once you're done with the redesign :)

**Comment by SerhiiCho** [comment]
![Screenshot 2023-08-31 at 10 49 27](https://github.com/brendt/rfc-vote/assets/35465417/6ec345fe-e5f6-45d3-b609-1a65577f753e)

**Comment by SerhiiCho** [comment]
I can even make 4 columns like this:

![image](https://github.com/brendt/rfc-vote/assets/35465417/8c3d1eeb-3296-4fc1-8d17-2fa2fe50a9c5)

The problem is that some people have long usernames

**Comment by Plytas** [comment]
I like the look of the text!. I guess no matter how big the block is, someone could add a super long name just for the sake of it. But since this is coming from the json file in the repo, there's more control over it?

**Comment by SerhiiCho** [comment]
I think it now looks good. I've made a condition for the name:

```php
mb_strlen($c->name) > 10 ? 'text-xs' : 'text-sm'
```

The only long name here is 'Ngô Quốc Đạt` and it looks good with small font:

![image](https://github.com/brendt/rfc-vote/assets/35465417/10643560-1010-4452-85b7-a573da67a823)

**Comment by brendt** [comment]
> It's kinda hard to gain it, whoever makes first arguments gets the most upvotes.

Well, it needs balancing, we'll improve it over time. But the system itself should play an important role. No worries though, we can improve on it later, it doesn't need to be present on this page just yet.

**Comment by brendt** [comment]
Looks great, btw! I think I like the aligned version slightly more, but that's just personal preference.
