### ISSUE TITLE
RFC's with multiple primary votes

### ISSUE THREAD

**Issue by nielsdos** [brendt/rfc-vote#207]
From https://wiki.php.net/rfc/voting under "Required Majority":

> For procedural reasons, multiple RFCs may be combined into one, in which case there may be multiple primary votes. Combining multiple RFCs into one does not allow turning a primary vote into a secondary vote. 

From what I understand, currently the website does not support this kind of RFC, right?

Past practical example: https://wiki.php.net/rfc/randomizer_additions

**Comment by brendt** [comment]
You're right, they are not supported right now. I don't think I want to complicate it on our side though.

- These kinds of RFCs don't happen all that often
- I'd prefer to make separate RFCs for them on our side, it'll keep things simpler (and I actually think it's better UX anyway, compared to trying to mix multiple votes into one)
