### ISSUE TITLE
User profile popup

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#23]
Whenever you hover over a username in the arguments, you should be shown a popup with its relevant user data: name, avatar, social links, reputation

**Comment by MohammadAlhallaq** [comment]
I may not have the eye of a designer, but I worked on this prototype during my lunch break. What do you think would be better colors, or maybe a more efficient way to organize the elements of the popup?


![Screenshot 2023-08-06 at 2 47 49 PM](https://github.com/brendt/rfc-vote/assets/19909432/c6a531d6-574c-4100-8057-6934d4fc4f2d)

**Comment by brendt** [comment]
It's definitely a start :) The people at Tighten are helping with the design, so as far as I'm concerned you can send this as a PR, and we can iterate on it later ;)
