### ISSUE TITLE
Frontend tests/Dusk tests

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#231]
We probably want to add some kind of frontend tests at this point, that go through the whole RFC browsing and voting flow. Individual unit tests of livewire components add some level of certainty, but I want to be sure we can deploy without actually clicking through the app, so I think we best add some Dusk tests.

**Comment by Plytas** [comment]
Caleb did a [livewire maintenance stream](https://youtu.be/mi-U3Wa2u-M) recently and he does have some nice helpers for dusk tests. Maybe someone could investigate into that.

**Comment by vsergiu93** [comment]
I would like to look in to this, probably I would not be able to finish everything but maybe I could get us started :).

**Comment by brendt** [comment]
Nice! Let me know if I can help :)
