### ISSUE TITLE
🌗 Code samples do not match the dark theme

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#238]
### Description
Code samples in RFC description and code samples inside arguments do not match the 🌗 dark theme. I think we should change it with highlight.js depending on which theme is on.

### RFC Description
![image](https://github.com/brendt/rfc-vote/assets/35465417/7cd60d41-6d82-4af6-8171-4542117d27f7)

### Argument
![image](https://github.com/brendt/rfc-vote/assets/35465417/88c13d78-6f4f-41bd-8a2b-651d7b5ff6a7)

**Comment by MohammadAlhallaq** [comment]
I'm trying to reproduce this locally but having no luck. What does the Markdown used here look like?

**Comment by brendt** [comment]
This is the description:

> The "pipe operator" `|>` allows you to chain multiple function calls in a more convenient way.
> 
> ```php
> $result = "Hello World"
>     |> 'htmlentities'
>     |> 'str_split'
>     |> fn($x) => array_map('strtoupper', $x)
>     |> fn($x) => array_filter($x, fn($v) => $v != 'O');
> ```
> 
> This RFC was already declined, but we're sharing it here as another test RFC, and because it'd be interesting to learn people's opinion about it.

**Comment by Erol314** [comment]
![image](https://github.com/brendt/rfc-vote/assets/24621490/3fd8869d-3f44-4392-ae0d-e40b4c18b41c)

**Comment by MohammadAlhallaq** [comment]
Okay! I must be doing something wrong or it's just trying to get on my nerves!!😅

![Screenshot 2023-08-31 at 11 13 57 PM](https://github.com/brendt/rfc-vote/assets/19909432/47c2f2ab-8688-4755-b2f4-179dbb7534a6)

![Screenshot 2023-08-31 at 11 14 03 PM](https://github.com/brendt/rfc-vote/assets/19909432/bd8abed9-6575-446a-a9f9-7301cfbe3d57)

**Comment by Plytas** [comment]
That might be the markdown parser converting stuff. Can you check what html is generated?

**Comment by MohammadAlhallaq** [comment]
this is what I'm getting here, I think it's getting it right!

![Screenshot 2023-08-31 at 11 36 24 PM](https://github.com/brendt/rfc-vote/assets/19909432/8bc253e7-cb39-43d5-9216-5b52de6ab9f9)

**Comment by Plytas** [comment]
It should be wrapped in `<pre>` so it is the parser, now it's parsing to an inline code block.

**Comment by Plytas** [comment]
This is how it looks locally.
<img width="517" alt="image" src="https://github.com/brendt/rfc-vote/assets/17316322/0d8005ad-564f-4c7c-ad9b-9aaf06956868">

**Comment by brendt** [comment]
Try removing the leading tabs within the codeblock?

**Comment by MohammadAlhallaq** [comment]
this is the markdown

```php
$user = factory::create([
'user' => 'mohammad',
]);
```
Unfortunately, still no luck, although I tried it live and it works just fine!! What could be messing up here!

**Comment by brendt** [comment]
> Unfortunately, still no luck, although I tried it live and it works just fine!! What could be messing up here!

You mean the code samples switch to dark mode for you?

**Comment by Plytas** [comment]
I believe code blocks turn to inline code blocks. As if it was using single back ticks.

**Comment by brendt** [comment]
Oh, gotcha. Maybe try via the seeder, see if it works there?

**Comment by MohammadAlhallaq** [comment]
> > Unfortunately, still no luck, although I tried it live and it works just fine!! What could be messing up here!
> 
> You mean the code samples switch to dark mode for you?

No, the code blocks provided to me worked on the live version but not locally. However, overall, I believe I'm too close to opening a pull request to fix this, as I've started to get the hang of it.

**Comment by SerhiiCho** [comment]
Closed with pull request #247
