### ISSUE TITLE
Clickable cards on the homepage

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#242]
Someone noted that the RFC cards are the homepage aren't in any way styled as clickable. It might make it confusing for people to know these are actually links. Maybe we should add some text? "Read more", or maybe an icon? Not sure.

**Comment by Plytas** [comment]
Maybe just a `hover:ring` class on them?

https://github.com/brendt/rfc-vote/assets/17316322/1327ca4c-3546-490c-819a-7a86a1092178

**Comment by brendt** [comment]
The problem with that is mobile though 🤔

**Comment by Plytas** [comment]
I see... Then maybe this icon in top right corner?
<img width="64" alt="image" src="https://github.com/brendt/rfc-vote/assets/17316322/e66fc9f2-e578-49e3-bfe3-bce96ff60876">

**Comment by brendt** [comment]
Something like that. Although that icon usually means "open in new tab".

But some kind of arrow might help? @SerhiiCho wdyt?

**Comment by SerhiiCho** [comment]
Idk, I like the current version, I think we passed that point when people needed a button to click, but I can see the advantage of a button. I like the idea of @brendt to add something like "Read more" link. You know one of those links that google likes adding. Here are some examples:

<img width="404" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/751c174f-a0ae-4389-911e-9f8429e370c4">

<img width="308" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/a227e21e-ac0f-4161-b629-00f84aa9d4b6">

**Comment by brendt** [comment]
Exactly, that seems like the best approach
