### ISSUE TITLE
Pagination Breaks After Edit

### ISSUE THREAD

**Issue by moebrowne** [brendt/rfc-vote#269]
# Reproduction

- Vote and create argument
- Edit argument and save
- Click on any page in the pagination.

The pagination links go to `https://rfc.stitcher.io/livewire/message/argument-list?page=2`. Which obviously doesn't work.

Suspect this has something to do with the pagination being based on the `previous` request.

**Comment by SerhiiCho** [comment]
Yep, I can confirm it. This is what I get locally:

<img width="1377" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/765529de-2db5-4581-9415-7792056e01ff">
