### ISSUE TITLE
Code block styling: small size

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#274]
<img width="1223" alt="Screenshot 2023-09-06 at 11 49 00" src="https://github.com/brendt/rfc-vote/assets/6905297/22f508f2-da67-4fec-b22f-5e2eaea84e6e">

https://rfc.stitcher.io/rfc/the-pipe-operator

**Comment by SerhiiCho** [comment]
Someone needs to remove `max-width: 200px;` from the `code` HTML element. Will you do it @MohammadAlhallaq? If you don't have time, I'll do it

**Comment by MohammadAlhallaq** [comment]
@SerhiiCho Please do it because I still can't produce code highlighting locally for some reason 😅
