### ISSUE TITLE
🐛 Error when trying to submit an argument

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#296]
When I'm on the arguments' page:

![image](https://github.com/brendt/rfc-vote/assets/35465417/4f6e7613-64d6-4837-aa38-fa209771fb9a)

I'm hitting submit button and get the error:

![image](https://github.com/brendt/rfc-vote/assets/35465417/1be9a9a4-5eef-43da-bf0a-b9af9b4a4862)

`The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`/opt/homebrew/bin/node /opt/homebrew/bin/npm root -g` /opt/homebrew/bin/node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/var\/www\/html\/storage\/1051508466-0531226001694417499\/index.html","action":"screenshot","options":{"type":"png","args":[],"viewport":{"width":1200,"height":627,"deviceScaleFactor":2},"displayHeaderFooter":false}}'" failed. Exit Code: 127(Command not found) Working directory: /var/www/html/public Output: ================ Error Output: ================ sh: 1: /opt/homebrew/bin/node: not found sh: 1: /opt/homebrew/bin/node: not found`

The binaries in the .env file are:
```
NODE_BINARY_PATH=/opt/homebrew/bin/node
NPM_BINARY_PATH=/opt/homebrew/bin/npm
```

I've tried to change them to:

```
NODE_BINARY_PATH=/usr/bin/node
NPM_BINARY_PATH=/usr/bin/npm
```

but it gives even a longer error message: `The command "PATH=$PATH:/usr/local/bin:/opt/homebrew/bin NODE_PATH=`/usr/bin/node /usr/bin/npm root -g` /usr/bin/node '/var/www/html/vendor/spatie/browsershot/src/../bin/browser.cjs' '{"url":"file:\/\/\/var\/www\/html\/storage\/1740280312-0865877001694417636\/index.html","action":"screenshot","options":{"type":"png","args":[],"viewport":{"width":1200,"height":627,"deviceScaleFactor":2},"displayHeaderFooter":false}}'" failed. Exit Code: 1(General error) Working directory: /var/www/html/public Output: ================ Error Output: ================ [1m[43m[30m Puppeteer old Headless deprecation warning:[0m[33m In the near future `headless: true` will default to the new Headless mode for Chrome instead of the old Headless implementation. For more information, please see https://developer.chrome.com/articles/new-headless/. Consider opting in early by passing `headless: "new"` to `puppeteer.launch()` If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.[0m Error: Could not find Chrome (ver. 116.0.5845.96). This can occur if either 1. you did not perform an installation before running the script (e.g. `npm install`) or 2. your cache path is incorrectly configured (which is: /home/sail/.cache/puppeteer). For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration. at ChromeLauncher.resolveExecutablePath (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:300:27) at ChromeLauncher.executablePath (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:182:25) at ChromeLauncher.computeLaunchArguments (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:98:37) at async ChromeLauncher.launch (/var/www/html/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:79:28) at async callChrome (/var/www/html/vendor/spatie/browsershot/bin/browser.cjs:92:23)`

- Computer Mac m1
- Environment is Sail (docker)

**Comment by vsergiu93** [comment]
@SerhiiCho, Unfortunately I didn't have time to look at this, basically this [line ](https://github.com/brendt/rfc-vote/blob/main/docker/8.2/Dockerfile#L21) works for all devices expect for the arm ones, in your case Mac m1. 
Basically you need chrome or chromium for browsershot which is used in a job to generated the meta image.

The fix would be somewhat similar to what was suggested [here](https://github.com/brendt/rfc-vote/pull/234#issuecomment-1700920222) somehow we need to specify what package to install based on cpu arhitecture, I think for mac m1,m2 chromium is needed, we could decide to use only chromium. Maybe if we only use chromium it will be a bit simpler to handle this.

**Comment by vsergiu93** [comment]
@SerhiiCho have you tried to install Rosetta 2? apparently this will allow you to run x86 docker images, please have a look here 
https://docs.docker.com/desktop/install/mac-install/

**Comment by SerhiiCho** [comment]
To vote for RFC, people need to install extra packages?

**Comment by vsergiu93** [comment]
Only for docker dev mode, in production is something else, and I think @brendt takes care of that. But locally with docker is a bit more complicated, and if I understand well from the linked articles Rosetta 2 will simplify a bit all of that because it will allow you to run docker images that are not specially built for arm.

**Comment by SerhiiCho** [comment]
> Unfortunately I didn't have time to look at this

No worries, I'll ditch Sail for now, it's causing too much issues for me. I'll use it locally with artisan serve

**Comment by vsergiu93** [comment]
@SerhiiCho One thing though, not sure if this issue should be labeled as a bug, because the feature works, is just that you need to have the environment properly set up and it works as expected. I think this issue is more about us defining all the ways you can start this project locally and work based on your machine, and improve the docs a bit so that users who are willing to contribute to this project ca do so relatively easy. Unfortunately I don't have access to a Mac laptop, therefore I would need some help with that part. 
@Erol314 As you mentioned [here](https://github.com/brendt/rfc-vote/pull/286#issuecomment-1712792544) that you are going to give this project a try on m2 mac, could you please also have a look at this  https://patrickwthomas.net/macos-docker/, it would be nice if this works well because it will simplify a lot the sail setup.

**Comment by SerhiiCho** [comment]
Makes sense

**Comment by brendt** [comment]
Just FYI, setting `BROWSERSHOT_FAKE=true` in your `.env` will skip all the image rendering and get rid of this error.
