### ISSUE TITLE
Code blocks lack contrast in bright mode

### ISSUE THREAD

**Issue by daiwai** [brendt/rfc-vote#365]
The code blocks in the bright mode have a very low contrast between the foreground and background. It appears that the text color remains the same as that in the dark mode, making the code almost impossible to read. 

![rfc_vote_code_bright_mode](https://github.com/brendt/rfc-vote/assets/683371/0db4de63-d08b-4939-be1b-26d59c6dd8d2)

The code blocks could also use some padding.

Tested in recent versions of Chromium (116) and Firefox (119) on Ubuntu.

**Comment by SerhiiCho** [comment]
Duplicate https://github.com/brendt/rfc-vote/issues/340

**Comment by SerhiiCho** [comment]
Thanks for reporting, but it already resolved in pull request https://github.com/brendt/rfc-vote/pull/341
It just hasn't been deployed yet. Only @brendt can do it, so we need to wait for him

**Comment by SerhiiCho** [comment]
This how it currently looks on the main branch:
<img width="1123" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/c08aaa4f-6dde-42fb-9e78-815e0f7a56a3">

**Comment by daiwai** [comment]
Thanks @SerhiiCho, did not see #340 as it is already closed.
