### ISSUE TITLE
unreadable code snippet when using ligth mode

### ISSUE THREAD

**Issue by bernard-ng** [brendt/rfc-vote#389]
to reproduce 
- go to an rfc detail page, 
- switch to ligth mode

![image](https://github.com/brendt/rfc-vote/assets/31113941/6ac76602-f919-42c4-be8c-1a74786b260b)

**Comment by SerhiiCho** [comment]
Duplicate https://github.com/brendt/rfc-vote/issues/365

**Comment by SerhiiCho** [comment]
Thanks for reporting, but it already resolved in pull request https://github.com/brendt/rfc-vote/pull/341
