### ISSUE TITLE
Rework voting/argument mechanics

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#57]
Much of the value of this platform comes not from the vote counter (which is a basic poll), but from the arguments, and upvotes on those arguments. This data gives much better insights in how the community feels, instead of a simple yes/no vote.

That's why we propose to make some changes:

- The concept of "vote" is removed, instead, a pro or con argument is the only thing a user can submit — essentially: making arguments required.
- The vote bar, however, doesn't show the amount of arguments. It shows the total amount of upvotes on arguments. The pro side is the sum of all upvotes for all pro arguments, the other way around for con arguments. This way, users can still cast a "simple vote" (actually they can cast several); BUT they are forced to read arguments, or even submit one themselves

Open questions:

- We could limit the amount of votes any user has per RFC. This would prevent simply upvoting all pro or con arguments
- This limit could increase based on a user's reputation. Added benefit: this adds an incentive for people to interact.
- We could also increase the amount of arguments a single user can make, a user could even make a pro and con argument if they want to.
- This argument limit again could be increased based on reputation, again adding incentive for people to interact.

Possible problems to overcome:

- Users need to understand that the vote bar shows the total amount of upvotes in the arguments, we need to communicate that clearly somehow.

TODO

- [x] auto update vote counters when argument gets a vote
- [x] #66
- [ ] #63
- [x] Clearly explain how voting works on the RFC page
- [ ] Minimum argument size
- [x] Be able to switch your vote? Probably requires a new argument. 
- [x] Get rid of `Vote` model once everything is migrated

**Comment by Wulfheart** [comment]
Wouldn't this weight more people who vote everything up or down?

**Comment by brendt** [comment]
- TODO: take care of changing your vote when you've voted

**Comment by brendt** [comment]
To reply @Wulfheart we can prevent issues here by only allowing a limited set of votes per user per RFC

**Comment by brendt** [comment]
I'm going to hold off on the minimal argument requirement until it becomes a problem. Closing for now
