### ISSUE TITLE
Use `Route::View` instead of single responsibility controllers

### ISSUE THREAD

**Issue by alirezasalehizadeh** [brendt/rfc-vote#70]
What do you think if we use `Route::view` method instead of single responsibility controllers that return only one view?
For example, instead of:
```php
<?php

namespace App\Http\Controllers;

final readonly class AboutController
{
    public function __invoke()
    {
        return view('about');
    }
}
```
Use this:
```php
// web.php

Route::view('/about', 'about');

```

It looks cleaner and removes redundant controller files.

**Comment by SerhiiCho** [comment]
Great tip, but it makes sense to keep the controller if there is gonna be logic on the about page in the future. But, I don't know if it will

**Comment by alirezasalehizadeh** [comment]
Thanks @SerhiiCho
For the `register` or `login` or other controllers, logic may be needed in the future, but for controllers such as `about` and etc, there is no logic other than displaying the view.

**Comment by brendt** [comment]
I like the effort, however, there's a good reason I move everything to controllers. I want to be able to always use `action` to generate URLs, which requires a controller class. So personally, I don't mind the extra couple of lines for more consistency.
