### ISSUE TITLE
Navigation Bar Redesign

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#71]
We can change a navigation bar to something like this:

![image](https://github.com/brendt/rfc-vote/assets/35465417/3a969c6a-4369-4a4b-abfc-adf2928ac593)

Here are some things that we can do related to the nav bar:
1. We can add a PHP logo since this platform is specific for php
2. We can change the font for "rfc votes" logo (later we can make a custom logo)
3. We can change the color of the navbar to dark blue to make more PHP related
4. The navigation bar itself has to have a `nav` HTML elements instead of the regular `div`.
5. We can add a container inside the navigation bar to fix the issue on the screenshot below that appears on wide screens:

![image](https://github.com/brendt/rfc-vote/assets/35465417/587ee40f-1981-40a2-b705-da9919e82c01)

We can make this dark blue as the main accent color and use it for other elements to make it look more consistent with colors.

I'd like to hear what others think about this.

**Comment by brendt** [comment]
> We can add a PHP logo since this platform is specific for php

I think we need to be careful though: people might think this is an official PHP project, which is not the case.

> We can change the font for "rfc votes" logo (later we can make a custom logo)

Makes sense to make a logo at one point (as well as a favicon) — I might ask a designer at JetBrains soon. I don't think we need a cursive font as a temporary placeholder. 

> We can change the color of the navbar to dark blue to make more PHP related

Isn't purple closer to PHP though? Right now we're using the default Tailwind colors, I'm not against changing it. I choose purple though exactly because of PHP.

> The navigation bar itself has to have a nav HTML elements instead of the regular div.

Seems like a good idea 👍

> We can add a container inside the navigation bar to fix the issue on the screenshot below that appears on wide screens:

Yes, we should definitely do that 👍

**Comment by SerhiiCho** [comment]
What about this version?:

<img width="1483" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/ae8b9329-5ca8-46f1-9836-601bbf8d7df4">

1. Added showing which link is active
2. Changed the user profile link
3. Reduced the vertical padding on the navbar
4. Added container inside the navbar to make it look nice on widescreens
5. Change HTML tag of the navbar from `<div></div>` to `<nav></nav>`

**Comment by brendt** [comment]
Oh I like that! Could you send a PR? :)

**Comment by SerhiiCho** [comment]
Thanks, I just pushed a PR
