### ISSUE TITLE
Usernames for users

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#82]
Users should automatically get a username, which is a unique slug representation of their (first) name. They should be able to change their username. It is also used as the slug for the public profile page.

**Comment by alirezasalehizadeh** [comment]
How about adding a username input to the register page instead of creating a username from the user (first) name?
In this way, the user can have a user name of his choice and the possibility of repetition is less.

**Comment by brendt** [comment]
Makes sense! Do you want to submit a PR for that?
