### ISSUE TITLE
Voting bar redesign (suggestion)

### ISSUE THREAD

**Issue by SerhiiCho** [brendt/rfc-vote#86]
I'm looking for different way to make a voting bar look better, just playing with different styles. The red color is awful, it's hard to fit it with green. I like this version:

<img width="1132" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/16f0e33c-7eac-4e55-871c-f76370b856c5">

Replace red with white, but it will contradict the other design decisions like these small red chips:
<img width="174" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/a42a9d87-0ef6-452a-a38f-723ec907df11">

Maybe it's worth getting rid of the red color completely? What do you guys think? That way we'll remove negative feeling to voting against the RFC and be able to make a pretty design.

This is what the voting bar looks like right now:
<img width="1215" alt="image" src="https://github.com/brendt/rfc-vote/assets/35465417/f7b6ab1d-f29a-4a12-889f-50a46095956a">

**Comment by brendt** [comment]
I don't think switching to grey or white for one of the types is the way to go. It feels like the progress bar should "fill up" with yes votes.

In some cases, the "no" vote might actually be the popular choice, so there shouldn't be an "inbalence" between the two.

I do agree that the current colors don't look all that good, maybe it's as simple as picking two custom colors, moving away from Tailwind's default colors.
