### ISSUE TITLE
Username as default

### ISSUE THREAD

**Issue by brendt** [brendt/rfc-vote#92]
- [ ] Show the username instead of the full name
- [ ] Make username a field during registration

**Comment by vsergiu93** [comment]
I would like to work on this one if is ok :)

**Comment by brendt** [comment]
Go for it!

**Comment by vsergiu93** [comment]
As I was working on this I realized that there are some unknowns:
1. Should we make the username field a required one meaning users cannot register without a username and we do not automatically generate it.
2. If we make the field required, I guess we do not need the `saving` hook on the User model
3. If we don't make the field required and we keep this logic of automatically generating a username, we need to do it on the front-end side, meaning as the user types his name we somehow display what the username will be, then the user has the chance to accept the automatically generated one or just write it's own.
4. Should we allow users to change their username after the account was created? 

This are some unknowns for me and I don't really want to chose by myself some solution.

**Comment by brendt** [comment]
> Should we make the username field a required one meaning users cannot register without a username and we do not automatically generate it.

Yes

> If we make the field required, I guess we do not need the saving hook on the User model

True

> If we don't make the field required and we keep this logic of automatically generating a username, we need to do it on the front-end side, meaning as the user types his name we somehow display what the username will be, then the user has the chance to accept the automatically generated one or just write it's own.

Would be nice to have, but not necessary. Feel free :)

> Should we allow users to change their username after the account was created?

Let's not allow that for now, as it might have unforeseen consequences. For example: I'm debating whether it's worth allowing comments on arguments, where people can tag eachother. It will be easier to have fixed usernames for the time being, we can always expand on it later.

**Comment by vsergiu93** [comment]
Thanks for clarifying things a bit. I also agree that we can keep it as simple as possible initially and build upon this later as we understand how this will all work.
